name: Comparación de tokens

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  comparar:
    runs-on: self-hosted
    steps:
      - name: CompararTokens
        env:
          DEV_TOKEN: ${{  secrets.DEV_TOKEN  }}
          LOCAL_PROD_TOKEN: ${{  secrets.LOCAL_PROD_TOKEN  }}
        shell: powershell
        run:
          if ($env:DEV_TOKEN - eq $env:LOCAL_PROD_TOKEN) {
            write-host "Los secrets coinciden"
          }
          else {
            write-host "Los secrets no coinciden"
          }
        
